### ISSUE TITLE
Crash in github.com/jackc/pgproto3/v2.Bind.MarshalJSON

### ISSUE THREAD

**Issue by wingedpig** [jackc/pgproto3#10]
Playing around with your proxy example, running Postgres 9.6.15, client is running lib/pq. Here's the relevant stack:

```
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
encoding/json.(*encodeState).marshal.func1(0xc000151ca8)
	/usr/local/go/src/encoding/json/encode.go:326 +0x85
panic(0x118f140, 0xc00019c1c0)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/jackc/pgproto3/v2.Bind.MarshalJSON(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0001863a0, 0x1, 0x1, ...)
	/Users/markf/src/groups.io/vendor/github.com/jackc/pgproto3/v2/bind.go:154 +0x4de
```

Here's a spew dump of the object being marshalled:

```
(*pgproto3.Bind)(0xc000144020)({
 DestinationPortal: (string) "",
 PreparedStatement: (string) "",
 ParameterFormatCodes: ([]int16) <nil>,
 Parameters: ([][]uint8) (len=1 cap=1) {
  ([]uint8) (len=17 cap=7938) {
   00000000  6f 77 6e 65 72 40 65 78  61 6d 70 6c 65 2e 63 6f  |owner@example.co|
   00000010  6d                                                |m|
  }
 },
 ResultFormatCodes: ([]int16) (len=7 cap=7) {
  (int16) 1,
  (int16) 1,
  (int16) 1,
  (int16) 1,
  (int16) 1,
  (int16) 0,
  (int16) 0
 }
})
```

Here's the output of the proxy program up to the crash:

```
F {"Type":"StartupMessage","ProtocolVersion":196608,"Parameters":{"application_name":"web","client_encoding":"UTF8","database":"userdb","datestyle":"ISO, MDY","extra_float_digits":"2","user":"groupsio"}}
B {}
B {"Type":"ParameterStatus","Name":"application_name","Value":"web"}
B {"Type":"ParameterStatus","Name":"client_encoding","Value":"UTF8"}
B {"Type":"ParameterStatus","Name":"DateStyle","Value":"ISO, MDY"}
B {"Type":"ParameterStatus","Name":"integer_datetimes","Value":"on"}
B {"Type":"ParameterStatus","Name":"IntervalStyle","Value":"postgres"}
B {"Type":"ParameterStatus","Name":"is_superuser","Value":"off"}
B {"Type":"ParameterStatus","Name":"server_encoding","Value":"UTF8"}
B {"Type":"ParameterStatus","Name":"server_version","Value":"9.6.15"}
B {"Type":"ParameterStatus","Name":"session_authorization","Value":"groupsio"}
B {"Type":"ParameterStatus","Name":"standard_conforming_strings","Value":"on"}
B {"Type":"ParameterStatus","Name":"TimeZone","Value":"US/Pacific"}
B {"Type":"BackendKeyData","ProcessID":76400,"SecretKey":1471443900}
B {"Type":"ReadyForQuery","TxStatus":"I"}
F {"Type":"Query","String":"BEGIN READ WRITE"}
B {"Type":"CommandComplete","CommandTag":"BEGIN"}
B {"Type":"ReadyForQuery","TxStatus":"T"}
F {"Type":"Query","String":"savepoint \"sp\""}
B {"Type":"CommandComplete","CommandTag":"SAVEPOINT"}
B {"Type":"ReadyForQuery","TxStatus":"T"}
F {"Type":"Parse","Name":"","Query":"SELECT * FROM emailalias WHERE emaillower=$1 FOR UPDATE","ParameterOIDs":null}
F {"Type":"Describe","ObjectType":"S","Name":""}
F {"Type":"Sync"}
B {"Type":"ParseComplete"}
B {"Type":"ParameterDescription","ParameterOIDs":[25]}
B {"Type":"RowDescription","Fields":[{"Name":"id","TableOID":436728,"TableAttributeNumber":1,"DataTypeOID":20,"DataTypeSize":8,"TypeModifier":-1,"Format":0},{"Name":"created","TableOID":436728,"TableAttributeNumber":2,"DataTypeOID":20,"DataTypeSize":8,"TypeModifier":-1,"Format":0},{"Name":"updated","TableOID":436728,"TableAttributeNumber":3,"DataTypeOID":20,"DataTypeSize":8,"TypeModifier":-1,"Format":0},{"Name":"version","TableOID":436728,"TableAttributeNumber":4,"DataTypeOID":20,"DataTypeSize":8,"TypeModifier":-1,"Format":0},{"Name":"userid","TableOID":436728,"TableAttributeNumber":5,"DataTypeOID":20,"DataTypeSize":8,"TypeModifier":-1,"Format":0},{"Name":"email","TableOID":436728,"TableAttributeNumber":6,"DataTypeOID":25,"DataTypeSize":-1,"TypeModifier":-1,"Format":0},{"Name":"emaillower","TableOID":436728,"TableAttributeNumber":7,"DataTypeOID":25,"DataTypeSize":-1,"TypeModifier":-1,"Format":0}]}
B {"Type":"ReadyForQuery","TxStatus":"T"}
```

A simple fix would be to check if `src.ParameterFormatCodes` is nil before indexing into it on line 154 of bind.go. But I don't know if this is a symptom of another issue.

**Comment by jackc** [comment]
I just pushed a change that should fix the nil case as well as the case where a single format code is provided for the entire row.

**Comment by wingedpig** [comment]
That fixed the crash. Thanks for the quick work!
